void FlarePrecache();
void FlareShowWep( edict_t *pEntity );
void FlareAttackStart( edict_t *pEntity );
void FlareReload( edict_t *pEntity );
void FlareSpawn( edict_t *pEntity );
void FlareTick( edict_t *pEntity );
void FlareAttackFly( edict_t *pEntity );
void FlareThink( edict_t *pent );
void FlareTouch( edict_t *pent, edict_t *pentTouch );
edict_t *FlareFindTarget( edict_t *pent );
void FlareKill( edict_t *pent);
